# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/selva88avc/user.git
    branch: master
- name: cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: selvakumar.ganesan2@cognizant.com
    password: #Infy123
    organization: IIHT Limited
    space: development
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - put: cf
    params:
      manifest: source-code/manifest.yml
      path: $(TargetFolder)/user-0.0.1-SNAPSHOT.jar



