package com.rabo.bank.user.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.rabo.bank.user.exception.UserNotFoundException;
import com.rabo.bank.user.model.User;
import com.rabo.bank.user.repository.UserRepository;

@Service
public class UserService {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	public User findByUserNameAndPassWord(String username, String password) {
		// TODO Auto-generated method stub
		User user = userRepository.findByUserNameAndPassWord(username, password);
		if(user==null) {
			throw new UserNotFoundException("User details not found");
		}
		return user;
	}
	public User findByUserId(int userId) {
		// TODO Auto-generated method stub
		User user = userRepository.findByUserId(userId);
		System.out.println("---------------"+user.getUserName());
		if(user==null) {
			throw new UserNotFoundException("User details not found");
		}
		return user;
	}
	public Iterable<User> findAll() {
		// TODO Auto-generated method stub
		Iterable<User> users = userRepository.findAll();
		if(users==null) {
			throw new UserNotFoundException("User details not found");
		}
		return users;
	}
	public User save(User user) {
		// TODO Auto-generated method stub
		User savedUser = userRepository.save(user);
		return savedUser;
	}
}
